version: "3.9"

name: chat-app
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/data/db
    ports:
      - ${MONGO_PORTS}
    networks:
      - chat-app

  backend:
    container_name: backend
    restart: unless-stopped
    mem_limit: 128m
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - mongodb
    networks:
      - chat-app

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - chat-app

networks:
  chat-app:
    driver: bridge
    name: chat-app
