version: "3.9"

name: chat-app
services:
  backend:
    container_name: backend
    restart: unless-stopped
    mem_limit: 512m
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - chat-app
      - coolify

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - chat-app

networks:
  chat-app:
    driver: bridge
    name: chat-app
  coolify:
    external: true
